<?php

require "data/posts.php";

$design = [
    $posts["design"][0],
    $posts["design"][1],
    $posts["design"][2]
];

$dev = [
    $posts["development"][0],
    $posts["development"][1],
    $posts["development"][2]
];

$accessibility = [
    $posts["accessibility"][0],
    $posts["accessibility"][1],
    $posts["accessibility"][2]
];

?>




<main id="home" class="p-3">
    <h1 class="text-center m-5">Ze blog</h1>
    <section class="my-5">
        <h2>Design</h2>
        <ul class="row p-0">
            
            <?php foreach($design as $design_item) { ?>
            
                <li class="col m-1">
                    <article class="card">
                        <header class="card-header p-0">
                            <img src="https://picsum.photos/id/1/550/250" class="card-img-top" alt="" />
                            <h3 class="card-title px-2 py-3">

                                <?= $design_item['title'] ?>

                            </h3>
                        </header>
                        <section class="card-body p-2">
                            <p class="card-text">

                                <?php echo $design_item['excerpt'] ?>

                            </p>
                        </section>
                        <footer class="p-2">
                            <a href="#" class="btn btn-primary">Lire l'article</a>
                        </footer>
                    </article>
                </li>
                
            <?php } ?>
            
        </ul>
    </section>
    <section class="my-5">
        <h2>Development</h2>
        <ul class="row p-0">

        <?php foreach($dev as $development_item) { ?>

            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/32/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">

                        <?= $development_item['title'] ?>

                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            <?php echo $development_item['excerpt'] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>

            <?php } ?>

        </ul>
    </section>
    <section class="my-5">
        <h2>Accessibility</h2>
        <ul class="row p-0">

        <?php foreach($accessibility as $accessibility_item) { ?>
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/67/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">


                        <?= $accessibility_item['content'] ?>
                        
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">

                        <?= $accessibility_item['content'] ?>

                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
</main>